name: Build

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Lint
        run: npm run lint
      - name: Upload docs to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: stremio-web
          path: build
      - name: Deploy docs to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: stremio-web